### ISSUE TITLE
Change Name problem.

### ISSUE THREAD

**Issue by Felix550** [MobinaJafarian/OnlineNewsSite#10]
Hi, i was experimenting with your GitHub project OnlineNewsSite and it work fine but when i change the project name es.NewsApp it give me 404 error and when i fix the error on index.php modyfing the Current_Domain value it work but just with the home page, Can you help me, THX.

**Comment by MobinaJafarian** [comment]
Hello, @Felix550 
Hope you doing well

You should also change the name of the project in the .htaccess file.

**Comment by Felix550** [comment]
Hi, thanks.for replying to me, now I am testing it on localhost with XAMPP, the problem is when I go to another page it sends me to the original name site.

**Comment by MobinaJafarian** [comment]
Did you configure your information in `index.php` and `.htaccess` files?

**Comment by Felix550** [comment]
Yes, in the .htacces file and in the index.php just the database info, mail and the BASE_DOMAIN and BASE_PATH

**Comment by MobinaJafarian** [comment]
Hi @Felix550 
Sorry for my late reply

For solving this issue follow these steps:

1. Make sure that the name of the project directory is the same as the domain name you want.
2. Update the desired name of the project in CURRENT_DOMAIN `index.php` file.
3. Update this line 
`RewriteRule ^(.+)$ {YourProjectName}/index.php [QSA,L]`
in the `.htaccess` file.

For example :
`RewriteRule ^(.+)$ es.NewsApp/index.php [QSA,L]`

---
I think you missed step 1
