### ISSUE TITLE
The activation email was not sent error

### ISSUE THREAD

**Issue by KALIDINDIPAVANTEJASATYAVARMA** [MobinaJafarian/OnlineNewsSite#13]
![ISSUE](https://github.com/MobinaJafarian/OnlineNewsSite/assets/133869526/8e04f680-940b-4e14-bc7b-84ff0f6c01db)

To resolve the issue, should we make any changes in this part of index.php: define('MAIL_HOST', 'sandbox.smtp.mailtrap.io');
define('SMTP_AUTH', 'LOGIN');
define('MAIL_USERNAME', 'yourMailUsername');
define('MAIL_PASSWORD', 'yourMailPassword');
define('MAIL_PORT', 587);
define('SENDER_MAIL', 'onlinenewssite@admin.com');
define('SENDER_NAME', 'admin');

**Comment by MobinaJafarian** [comment]
Yes, that's right, you have to configure your email, for example, you can
use the mailtap tool.

**Comment by KALIDINDIPAVANTEJASATYAVARMA** [comment]
Could you please tell how to configure the email using mailtrap and what are the necessary changes to be made in the index.php

**Comment by MobinaJafarian** [comment]
@KALIDINDIPAVANTEJASATYAVARMA 
First, follow these steps [README.md](https://github.com/MobinaJafarian/OnlineNewsSite?tab=readme-ov-file#setup)

And then you can use these tutorials

- https://www.youtube.com/watch?v=AveaJc6c3fI
- https://help.mailtrap.io/article/5-testing-integration

**Comment by KALIDINDIPAVANTEJASATYAVARMA** [comment]
The activation mail is now being shown in my mail trap inbox where i can click and activate but it is not being actually directly sent to the person's mail.And also isn't there a logout option for user

**Comment by MobinaJafarian** [comment]
I will add this option ASAP
