### ISSUE TITLE
Error is coming

### ISSUE THREAD

**Issue by Adithya03-bit** [MobinaJafarian/OnlineNewsSite#9]
![IMG_20230405_124843~2.jpg](https://user-images.githubusercontent.com/76038224/230009350-39e4599c-02c5-428c-b1e0-d4b75ad653e2.jpg)

**Comment by MobinaJafarian** [comment]
Hello 
Did you create a database named (news-project) ?

**Comment by Adithya03-bit** [comment]
Yes

**Comment by MobinaJafarian** [comment]
Make sure you are following setup guide in [README.md](https://github.com/MobinaJafarian/OnlineNewsSite/blob/develop/README.md) file.
And It'll run without problems.
